version: '3.7'
services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: claude_simweb_sql
    environment:
      - PMA_ARBITRARY=1
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.claude_simweb_sql-secure.entrypoints=websecure"
      - "traefik.http.routers.claude_simweb_sql-secure.middlewares=user-auth@file"
      - "traefik.http.routers.claude_simweb_sql-secure.rule=Host(`db.${DOMAIN}`)"


networks:
  proxy:
    external: true